'use client';

import { useState } from 'react';
import Papa from 'papaparse';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

interface ExportButtonsProps {
  reportType: 'appointments' | 'patients' | 'diseases';
  serviceName: string;
  startDate: string;
  endDate: string;
  barangayId?: number;
  requiresAppointment?: boolean;
  requiresMedicalRecord?: boolean;
}

export default function ExportButtons({
  reportType,
  serviceName,
  startDate,
  endDate,
  barangayId,
  requiresAppointment,
  requiresMedicalRecord,
}: ExportButtonsProps) {
  const [exporting, setExporting] = useState(false);
  const [exportFormat, setExportFormat] = useState<'csv' | 'pdf' | null>(null);

  // Check if export is allowed based on service permissions
  const canExport = () => {
    if (reportType === 'appointments' && !requiresAppointment) {
      return false;
    }
    if (reportType === 'diseases' && !requiresMedicalRecord) {
      return false;
    }
    return true;
  };

  const handleExport = async (format: 'csv' | 'pdf') => {
    if (!canExport()) {
      alert('You do not have permission to export this report type.');
      return;
    }

    setExporting(true);
    setExportFormat(format);

    try {
      // Fetch export data from API
      const response = await fetch('/api/healthcare-admin/reports/export', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: reportType,
          format,
          start_date: startDate,
          end_date: endDate,
          barangay_id: barangayId,
        }),
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Export failed');
      }

      const result = await response.json();
      const { data, metadata } = result;

      if (!data || data.length === 0) {
        alert('No data available to export for the selected filters.');
        return;
      }

      // Generate export based on format
      if (format === 'csv') {
        exportToCSV(data, metadata.filename);
      } else if (format === 'pdf') {
        exportToPDF(data, metadata);
      }

    } catch (error) {
      console.error('Export error:', error);
      alert(error instanceof Error ? error.message : 'Failed to export data. Please try again.');
    } finally {
      setExporting(false);
      setExportFormat(null);
    }
  };

  const exportToCSV = (data: any[], filename: string) => {
    try {
      // Convert data to CSV using papaparse
      const csv = Papa.unparse(data);

      // Create blob and download
      const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${filename}.csv`;
      link.click();
      URL.revokeObjectURL(url);

    } catch (error) {
      console.error('CSV export error:', error);
      alert('Failed to generate CSV file. Please try again.');
    }
  };

  const exportToPDF = (data: any[], metadata: any) => {
    try {
      // Create new PDF document
      const doc = new jsPDF('landscape');

      // Add header
      doc.setFontSize(18);
      doc.text(`${serviceName} - ${reportType.charAt(0).toUpperCase() + reportType.slice(1)} Report`, 14, 20);

      // Add metadata
      doc.setFontSize(10);
      doc.text(`Date Range: ${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`, 14, 30);
      doc.text(`Generated: ${new Date(metadata.generated_at).toLocaleString()}`, 14, 36);
      doc.text(`Generated by: ${metadata.generated_by}`, 14, 42);

      // Extract table headers and rows
      const headers = Object.keys(data[0] || {});
      const rows = data.map(row => headers.map(header => row[header]));

      // Add table
      autoTable(doc, {
        head: [headers],
        body: rows,
        startY: 50,
        styles: { fontSize: 8 },
        headStyles: { fillColor: [59, 130, 246] }, // Blue header
        alternateRowStyles: { fillColor: [245, 247, 250] },
        margin: { top: 50 },
      });

      // Add footer with page numbers
      const pageCount = (doc as any).internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.text(
          `Page ${i} of ${pageCount}`,
          doc.internal.pageSize.getWidth() / 2,
          doc.internal.pageSize.getHeight() - 10,
          { align: 'center' }
        );
      }

      // Save PDF
      doc.save(`${metadata.filename}.pdf`);

    } catch (error) {
      console.error('PDF export error:', error);
      alert('Failed to generate PDF file. Please try again.');
    }
  };

  const handleComprehensiveExport = async () => {
    setExporting(true);
    setExportFormat('csv'); // Using csv state for loading indicator

    try {
      // Fetch comprehensive export data from API
      const response = await fetch('/api/healthcare-admin/reports/export', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: 'comprehensive',
          format: 'excel',
          start_date: startDate,
          end_date: endDate,
          barangay_id: barangayId,
        }),
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Export failed');
      }

      const result = await response.json();
      const { data, metadata } = result;

      if (!data || (!data.appointments?.length && !data.patients?.length && !data.diseases?.length)) {
        alert('No data available to export for the selected filters.');
        return;
      }

      // Generate multi-sheet Excel file
      exportToExcel(data, metadata);

    } catch (error) {
      console.error('Comprehensive export error:', error);
      alert(error instanceof Error ? error.message : 'Failed to export data. Please try again.');
    } finally {
      setExporting(false);
      setExportFormat(null);
    }
  };

  const exportToExcel = (data: any, metadata: any) => {
    try {
      // Create a new workbook
      const workbook = XLSX.utils.book_new();

      // Sheet 1: Summary Statistics
      const summaryData = [
        ['Comprehensive Report'],
        ['Service', metadata.service],
        ['Generated By', metadata.generated_by],
        ['Generated At', new Date(metadata.generated_at).toLocaleString()],
        ['Date Range', `${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`],
        ['Barangay Filter', metadata.filters.barangay_id ? `ID: ${metadata.filters.barangay_id}` : 'All Barangays'],
        [],
        ['Summary Statistics'],
        ['Total Appointments', data.summary?.total_appointments || 0],
        ['Completed Appointments', data.summary?.completed_appointments || 0],
        ['Scheduled Appointments', data.summary?.scheduled_appointments || 0],
        ['Cancelled Appointments', data.summary?.cancelled_appointments || 0],
        ['Total Patients', data.summary?.total_patients || 0],
        ['Active Patients', data.summary?.active_patients || 0],
        ['Total Disease Cases', data.summary?.total_disease_cases || 0],
      ];
      const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
      XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

      // Sheet 2: Appointments (if available)
      if (data.appointments && data.appointments.length > 0) {
        const appointmentsSheet = XLSX.utils.json_to_sheet(data.appointments);
        XLSX.utils.book_append_sheet(workbook, appointmentsSheet, 'Appointments');
      }

      // Sheet 3: Patients (if available)
      if (data.patients && data.patients.length > 0) {
        const patientsSheet = XLSX.utils.json_to_sheet(data.patients);
        XLSX.utils.book_append_sheet(workbook, patientsSheet, 'Patients');
      }

      // Sheet 4: Diseases (if available)
      if (data.diseases && data.diseases.length > 0) {
        const diseasesSheet = XLSX.utils.json_to_sheet(data.diseases);
        XLSX.utils.book_append_sheet(workbook, diseasesSheet, 'Diseases');
      }

      // Save the workbook
      XLSX.writeFile(workbook, `${metadata.filename}.xlsx`);

    } catch (error) {
      console.error('Excel export error:', error);
      alert('Failed to generate Excel file. Please try again.');
    }
  };

  if (!canExport()) {
    return null;
  }

  return (
    <div className="flex gap-3">
      <button
        onClick={handleComprehensiveExport}
        disabled={exporting}
        className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white font-medium rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      >
        {exporting ? (
          <>
            <svg className="animate-spin h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            <span>Exporting...</span>
          </>
        ) : (
          <>
            <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 10h18M3 14h18m-9-4v8m-7 0h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
            <span>Export Report</span>
          </>
        )}
      </button>
    </div>
  );
}
